// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC00HUDPDsLYZoDaJeJxEhWb0w4aN13NbE',
    appId: '1:710061719815:web:161f5cb226804cdfb105a2',
    messagingSenderId: '710061719815',
    projectId: 'calculation-8a378',
    authDomain: 'calculation-8a378.firebaseapp.com',
    databaseURL: 'https://calculation-8a378-default-rtdb.firebaseio.com',
    storageBucket: 'calculation-8a378.appspot.com',
    measurementId: 'G-GLQTK92JC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjakXzhHUi4QSA-iKshcNZW3j12YEN0Uo',
    appId: '1:710061719815:android:8026992345e0d30ab105a2',
    messagingSenderId: '710061719815',
    projectId: 'calculation-8a378',
    databaseURL: 'https://calculation-8a378-default-rtdb.firebaseio.com',
    storageBucket: 'calculation-8a378.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHfp-t2Z5JMVjaQai1Ztq5-4h_6UZt1c8',
    appId: '1:710061719815:ios:802ac08277d73bd4b105a2',
    messagingSenderId: '710061719815',
    projectId: 'calculation-8a378',
    databaseURL: 'https://calculation-8a378-default-rtdb.firebaseio.com',
    storageBucket: 'calculation-8a378.appspot.com',
    iosBundleId: 'com.example.calcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHfp-t2Z5JMVjaQai1Ztq5-4h_6UZt1c8',
    appId: '1:710061719815:ios:802ac08277d73bd4b105a2',
    messagingSenderId: '710061719815',
    projectId: 'calculation-8a378',
    databaseURL: 'https://calculation-8a378-default-rtdb.firebaseio.com',
    storageBucket: 'calculation-8a378.appspot.com',
    iosBundleId: 'com.example.calcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC00HUDPDsLYZoDaJeJxEhWb0w4aN13NbE',
    appId: '1:710061719815:web:a25f026b2f377debb105a2',
    messagingSenderId: '710061719815',
    projectId: 'calculation-8a378',
    authDomain: 'calculation-8a378.firebaseapp.com',
    databaseURL: 'https://calculation-8a378-default-rtdb.firebaseio.com',
    storageBucket: 'calculation-8a378.appspot.com',
    measurementId: 'G-4L32Z6GJSN',
  );
}
